# Generated by Django 5.0.6 on 2024-07-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_options_customuser_is_staff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("users.update_all", "Can update all users"),
                    ("users.delete_all", "Can delete all users"),
                    ("users.update_self", "Can self update"),
                    ("users.delete_self", "Can self delete"),
                ]
            },
        ),
    ]
